<a href="https://colab.research.google.com/github/PuttupuR/My-Project/blob/main/DataPreprocessing_Assignment11_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Data.csv

**Step 1: Importing the libraries**

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix

**Step 2: Importing dataset**

In [3]:
data=pd.read_csv("/content/Data.csv")
data

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

**Step 3: Handling the missing data**

In [8]:
data.shape

(10, 4)

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes


In [5]:
data.size

40

In [6]:
data.isnull().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [16]:
data['Age'].mean()

38.77777777777778

In [17]:
data['Salary'].mean()

63777.77777777778

In [18]:
col=list(data.columns)
col

['Country', 'Age', 'Salary', 'Purchased']

In [19]:
for col_name in col:
  print(col_name)

Country
Age
Salary
Purchased


In [20]:
for col_name in col:
   if data[col_name].dtypes=='object':
     #print('ob')
     data[col_name] = data[col_name].fillna(data[col_name].mode()[0])
   else:
     #print('num')  
     data[col_name] = data[col_name].fillna(data[col_name].mean())

In [21]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     object 
 1   Age        10 non-null     float64
 2   Salary     10 non-null     float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes


In [22]:
data.isna().sum()

Country      0
Age          0
Salary       0
Purchased    0
dtype: int64

**Step 4: Encoding categorical data**

In [24]:
col_list=[]
for col in data.columns:
  if ((data[col].dtype=='object')&(col!='y')):
    col_list.append(col)

In [25]:
col_list

['Country', 'Purchased']

In [26]:
from sklearn.preprocessing import LabelEncoder
labelencoder=LabelEncoder()
for i in col_list:
  data[i]=labelencoder.fit_transform(data[i])

In [27]:
data.head(5)

Country   Age        Salary  Purchased
0        0  44.0  72000.000000          0
1        2  27.0  48000.000000          1
2        1  30.0  54000.000000          0
3        2  38.0  61000.000000          0
4        1  40.0  63777.777778          1

In [28]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     int64  
 1   Age        10 non-null     float64
 2   Salary     10 non-null     float64
 3   Purchased  10 non-null     int64  
dtypes: float64(2), int64(2)
memory usage: 448.0 bytes


**Step 5: Creating a dummy variable**

In [29]:
data1={"Country":["India","USA"],"Age":[21,64],"Salary":[62000,34000],"Purchased":["Yes","No"]}

In [30]:
data1

{'Country': ['India', 'USA'],
 'Age': [21, 64],
 'Salary': [62000, 34000],
 'Purchased': ['Yes', 'No']}

In [31]:
df=pd.DataFrame(data1)
df

Country  Age  Salary Purchased
0   India   21   62000       Yes
1     USA   64   34000        No

**Step 6: Splitting the datasets into training sets and Test sets**

In [34]:
x=data.loc[:,['Country','Age','Salary','Purchased']]
y=data.iloc[:,-1]
y

0    0
1    1
2    0
3    0
4    1
5    1
6    0
7    1
8    0
9    1
Name: Purchased, dtype: int64

In [35]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8,random_state=0)

In [36]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(8, 4)
(8,)
(2, 4)
(2,)


**Step 7: Feature Scaling**

In [38]:
from sklearn import preprocessing
min_max_scaler = preprocessing.MinMaxScaler(feature_range =(0, 1))

In [40]:
# Scaled feature
x_after_min_max_scaler = min_max_scaler.fit_transform(x)
  
print ("\nAfter min max Scaling : \n", x_after_min_max_scaler)
  
  
""" Standardisation """
  
Standardisation = preprocessing.StandardScaler()
  
# Scaled feature
x_after_Standardisation = Standardisation.fit_transform(x)
  
print ("\nAfter Standardisation : \n", x_after_Standardisation)


After min max Scaling : 
 [[0.         0.73913043 0.68571429 0.        ]
 [1.         0.         0.         1.        ]
 [0.5        0.13043478 0.17142857 0.        ]
 [1.         0.47826087 0.37142857 0.        ]
 [0.5        0.56521739 0.45079365 1.        ]
 [0.         0.34782609 0.28571429 1.        ]
 [1.         0.51207729 0.11428571 0.        ]
 [0.         0.91304348 0.88571429 1.        ]
 [0.5        1.         1.         0.        ]
 [0.         0.43478261 0.54285714 1.        ]]

After Standardisation : 
 [[-1.08347268e+00  7.58874362e-01  7.49473254e-01 -1.00000000e+00]
 [ 1.32424438e+00 -1.71150388e+00 -1.43817841e+00  1.00000000e+00]
 [ 1.20385853e-01 -1.27555478e+00 -8.91265492e-01 -1.00000000e+00]
 [ 1.32424438e+00 -1.13023841e-01 -2.53200424e-01 -1.00000000e+00]
 [ 1.20385853e-01  1.77608893e-01  6.63219199e-16  1.00000000e+00]
 [-1.08347268e+00 -5.48972942e-01 -5.26656882e-01  1.00000000e+00]
 [ 1.32424438e+00  0.00000000e+00 -1.07356980e+00 -1.00000000e+00]
 [-1.0