<a href="https://colab.research.google.com/github/PuttupuR/My-Project/blob/main/KNN_Mar_13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
#ML -->Sklearn

from sklearn.datasets import make_regression # you can create synthetic datasets

X,Y = make_regression(n_samples = 100, n_features = 3, n_targets =1, n_informative = 2)

#X-->input, Y-->Output

In [3]:
X.shape

(100, 3)

In [4]:
type(X)

numpy.ndarray

In [6]:
Y.shape

(100,)

In [7]:
df = pd.DataFrame(X, columns = ['X1','X2','X3'])

In [8]:
df.head()

X1        X2        X3
0  0.831721 -1.264685 -0.531971
1 -0.498317 -0.116529  0.510463
2 -0.807951 -0.107418  0.898376
3 -0.934490 -0.188699  0.675892
4  1.017744 -1.310456  0.733259

In [9]:
df["Y"] = Y

In [10]:
df

X1        X2        X3           Y
0   0.831721 -1.264685 -0.531971   65.362445
1  -0.498317 -0.116529  0.510463  -45.992858
2  -0.807951 -0.107418  0.898376  -73.933907
3  -0.934490 -0.188699  0.675892  -86.016887
4   1.017744 -1.310456  0.733259   81.834008
..       ...       ...       ...         ...
95  1.002841  1.905935 -0.023144  105.619444
96 -1.874557 -0.507370  1.162492 -173.554025
97 -0.153308  1.036775  0.526020   -5.767998
98 -1.089492 -0.964012  0.550811 -106.098294
99 -0.493874  0.147681 -1.274717  -43.526257

[100 rows x 4 columns]

In [11]:
df['X1'].shape

(100,)

In [12]:
df['X1'].values.shape

(100,)

In [13]:
from sklearn.neighbors import KNeighborsRegressor

# Stack the X1, X2, and X3 columns of df into a two-dimensional numpy array
x = np.column_stack((df['X1'], df['X2'], df['X3']))

# In this case, -1 is used to represent the unknown number of samples in the original X array, and 3 represents the number of features.
x = x.reshape(-1,3)
model = KNeighborsRegressor(n_neighbors = 1)
model.fit(x,df['Y'])

KNeighborsRegressor(n_neighbors=1)

In [14]:
df.head(5)

X1        X2        X3          Y
0  0.831721 -1.264685 -0.531971  65.362445
1 -0.498317 -0.116529  0.510463 -45.992858
2 -0.807951 -0.107418  0.898376 -73.933907
3 -0.934490 -0.188699  0.675892 -86.016887
4  1.017744 -1.310456  0.733259  81.834008

In [15]:
x.shape

(100, 3)

In [21]:
model.predict([[-0.9831721,-1.7364685,0.631971]]) # its predicting the output based on input values
#by default the distance metric is euclidean

array([-88.82055308])

In [ ]:
#metric -->euclidean, manhattan, cosine...
#type of averaging
#changing the no of neighbors

In [22]:
model.predict([[0.96,0.042,0.86],[1.715698,-0.306692,0.392501]])

array([ 59.88878182, 124.880447  ])

In [ ]:
#type of averaging
#changing the no of neighbors

In [24]:
from sklearn.neighbors import KNeighborsRegressor

# Stack the X1, X2, and X3 columns of df into a two-dimensional numpy array
x = np.column_stack((df['X1'], df['X2'], df['X3']))

# In this case, -1 is used to represent the unknown number of samples in the original X array, and 3 represents the number of features.
x = x.reshape(-1,3)
model = KNeighborsRegressor(n_neighbors = 2, weights = 'uniform')
#uniform means weighted averaging
#distance means weighted averaging
#by changing the parameter weights
model.fit(x,df['Y'])

KNeighborsRegressor(n_neighbors=2)

In [25]:
model.predict([[-0.308990,-0.535498,1.098157]])

array([-35.336697])

In [26]:
from sklearn.neighbors import KNeighborsRegressor

# Stack the X1, X2, and X3 columns of df into a two-dimensional numpy array
x = np.column_stack((df['X1'], df['X2'], df['X3']))

# In this case, -1 is used to represent the unknown number of samples in the original X array, and 3 represents the number of features.
x = x.reshape(-1,3)
model = KNeighborsRegressor(n_neighbors = 2, weights = 'uniform',metric = 'manhattan')
#uniform means weighted averaging
#distance means weighted averaging
#by changing the parameter weights
model.fit(x,df['Y'])

KNeighborsRegressor(metric='manhattan', n_neighbors=2)

In [27]:
model.predict([[-0.308990,-0.535498,1.098157]])

array([-9.40069548])

In [28]:
model = KNeighborsRegressor(n_neighbors = 1)
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,df['Y'],test_size = 0.3,random_state = 1)

In [29]:
x_train.shape

(70, 3)

In [30]:
x_test.shape

(30, 3)

In [31]:
y_train.shape,y_test.shape

((70,), (30,))

In [32]:
x_train

array([[-0.07225832,  1.25159902, -1.4875371 ],
       [-0.49387388,  0.14768132, -1.27471675],
       [-0.27157236,  0.32082095,  0.89596072],
       [ 1.00284055,  1.90593545, -0.02314386],
       [ 1.47289655,  0.39861124,  0.48335034],
       [-0.96520691, -0.99729023,  0.79369781],
       [-0.65446514,  0.97138637, -1.28996942],
       [ 0.14412757, -0.76687544, -0.24663914],
       [ 0.40713903, -0.43072009, -1.19004166],
       [-1.10627666,  0.39265588, -0.06733535],
       [-0.40830218, -1.57428068,  1.36858029],
       [-0.41068797,  0.46295266, -1.37546376],
       [ 0.29608309,  0.43597968, -0.80625965],
       [ 1.56569282, -0.8544273 ,  1.68904417],
       [-1.28196034, -0.86608717,  1.54537077],
       [ 0.36688009,  0.46742558, -0.82958043],
       [ 1.89946006, -1.34477691, -0.03407621],
       [ 0.05347006, -0.20179411,  1.0872324 ],
       [-2.63352875, -1.28959359, -0.81338295],
       [-1.08949212, -0.96401155,  0.55081063],
       [-0.13888914, -0.46051312, -0.935

In [33]:
model.fit(x_train,y_train)

KNeighborsRegressor(n_neighbors=1)

In [34]:
preds = model.predict(x_test)
preds

array([ 105.61944385,   -0.76731878,   -8.04907507,   42.09365642,
        121.35108259,  -12.52868906,   64.7684028 , -126.70866936,
        -49.24051697, -110.35905919,  -59.51658882,   16.8223137 ,
         68.1883075 ,  -43.52625731,  -95.11438297,  -99.8466938 ,
        134.96995524,  -97.01543266,  -79.97688027,   68.1883075 ,
        -86.01688724,  161.33382905,  -10.45461096,   81.83400784,
         68.1883075 ,  136.36632895,    7.04651944,   -8.63975254,
        108.42515965,  108.42515965])

In [35]:
y_test #(actual values ofyour test set )

80     88.499598
84     34.420441
33      8.568825
81      6.459000
93     74.806082
17    -72.209658
36     74.222354
82   -105.647619
69      7.119959
65    -95.391155
92    -81.861134
39      5.400511
56     69.258782
52    -31.770343
51    -88.820553
32    -79.746691
31    101.804812
44    -96.042556
78   -104.902540
10     64.663624
2     -73.933907
73    149.226982
97     -5.767998
62     71.286329
19     70.502394
35    124.880447
94     32.107153
27     22.588589
46    132.583967
38     70.330335
Name: Y, dtype: float64

In [36]:
error = np.abs(preds - y_test).sum() #sum of absolute errors
error

619.9711395665073

In [37]:
#evaluation metrics
#below are the regression evaluation metrics

In [38]:
np.abs(preds -y_test).mean() #Mean absolute error

20.66570465221691

In [39]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(preds,y_test)

20.66570465221691

In [40]:
from sklearn.metrics import mean_squared_error
mean_squared_error(preds,y_test)

662.9154824437658

In [41]:
#just putting all in one

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,df['Y'],test_size = 0.3,random_state = 1)

results = []
for num_neighbors in range(1,15):
  model = KNeighborsRegressor(n_neighbors = num_neighbors)
  model.fit(x_train,y_train)
  preds = model.predict(x_test)
  print("k-->",num_neighbors, "MAE-->",mean_absolute_error(preds,y_test))
  results.append(mean_absolute_error(preds,y_test))

k--> 1 MAE--> 20.66570465221691
k--> 2 MAE--> 20.413248839092905
k--> 3 MAE--> 19.532599024733848
k--> 4 MAE--> 20.06873385089522
k--> 5 MAE--> 19.87995074886105
k--> 6 MAE--> 21.954214897677428
k--> 7 MAE--> 19.486317943686423
k--> 8 MAE--> 16.449810000844156
k--> 9 MAE--> 16.872605252515452
k--> 10 MAE--> 19.377778615317244
k--> 11 MAE--> 19.59089872686932
k--> 12 MAE--> 20.59021833293706
k--> 13 MAE--> 21.42572979739062
k--> 14 MAE--> 22.444521844705946


In [42]:
results.index(min(results)) +1  # Best number of neighbors

8

In [43]:
from sklearn.model_selection import cross_val_score,KFold
kf = KFold(n_splits = 10)
model = KNeighborsRegressor(n_neighbors = 1)
cross_val_score(model,x,df['Y'], cv = kf, scoring = 'neg_mean_absolute_error' ).mean()

-25.786878829762667

In [44]:
results = []
for num_neighbors in range(1,11):
  model = KNeighborsRegressor(n_neighbors = num_neighbors)
  print("K-->",num_neighbors, "Average NMAE across 10 folds: ",cross_val_score(model,x,df['Y'], cv = kf, scoring = 'neg_mean_absolute_error' ).mean())
  results.append(cross_val_score(model,x,df['Y'], cv = kf, scoring = 'neg_mean_absolute_error' ).mean())

K--> 1 Average NMAE across 10 folds:  -25.786878829762667
K--> 2 Average NMAE across 10 folds:  -21.230440119708256
K--> 3 Average NMAE across 10 folds:  -19.773932832610818
K--> 4 Average NMAE across 10 folds:  -20.269555707492977
K--> 5 Average NMAE across 10 folds:  -20.721326993623695
K--> 6 Average NMAE across 10 folds:  -21.51504641141893
K--> 7 Average NMAE across 10 folds:  -22.439743505968988
K--> 8 Average NMAE across 10 folds:  -23.323658998526966
K--> 9 Average NMAE across 10 folds:  -23.736722575140316
K--> 10 Average NMAE across 10 folds:  -24.33396433376799


In [45]:
results.index(max(results))+1

3

In [ ]:
##Try tuning the following hyper-parameters
#metric -->euclidean, manhattan, cosine...
#type of averaging
#changing the no of neighbors

In [46]:
results = []
counter = 0
for num_neighbors in range(1,11):
  for d_metric in ['euclidean','manhattan']: #2 combinations for distance metric
    for avg_type in ['uniform','distance']: # combination for type of averaging
       model = KNeighborsRegressor(n_neighbors = num_neighbors)
       print(counter, "(",num_neighbors,',',d_metric,',',avg_type,')',",","Average NMAE across 10 folds: ",cross_val_score(model,x,df['Y'], cv = kf, scoring = 'neg_mean_absolute_error' ).mean(),sep ='')
       results.append(cross_val_score(model,x,df['Y'], cv = kf, scoring = 'neg_mean_absolute_error' ).mean())
       counter = counter + 1

0(1,euclidean,uniform),Average NMAE across 10 folds: -25.786878829762667
1(1,euclidean,distance),Average NMAE across 10 folds: -25.786878829762667
2(1,manhattan,uniform),Average NMAE across 10 folds: -25.786878829762667
3(1,manhattan,distance),Average NMAE across 10 folds: -25.786878829762667
4(2,euclidean,uniform),Average NMAE across 10 folds: -21.230440119708256
5(2,euclidean,distance),Average NMAE across 10 folds: -21.230440119708256
6(2,manhattan,uniform),Average NMAE across 10 folds: -21.230440119708256
7(2,manhattan,distance),Average NMAE across 10 folds: -21.230440119708256
8(3,euclidean,uniform),Average NMAE across 10 folds: -19.773932832610818
9(3,euclidean,distance),Average NMAE across 10 folds: -19.773932832610818
10(3,manhattan,uniform),Average NMAE across 10 folds: -19.773932832610818
11(3,manhattan,distance),Average NMAE across 10 folds: -19.773932832610818
12(4,euclidean,uniform),Average NMAE across 10 folds: -20.269555707492977
13(4,euclidean,distance),Average NMAE acro

In [47]:
results.index(max(results))

8

In [48]:
from sklearn.model_selection import GridSearchCV
model = KNeighborsRegressor(n_jobs=-1)
kf = KFold(n_splits = 10)

params = {'n_neighbors':list(range(1,11)),
          'weights':['uniform','distance'],
          'metric':['euclidean','manhattan','cosine']
         }

gcv = GridSearchCV(model,param_grid = params, cv= kf, scoring ='neg_mean_absolute_error')
gcv.fit(x,df['Y'])


GridSearchCV(cv=KFold(n_splits=10, random_state=None, shuffle=False),
             estimator=KNeighborsRegressor(n_jobs=-1),
             param_grid={'metric': ['euclidean', 'manhattan', 'cosine'],
                         'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                         'weights': ['uniform', 'distance']},
             scoring='neg_mean_absolute_error')

In [49]:
gcv.best_params_

{'metric': 'manhattan', 'n_neighbors': 3, 'weights': 'distance'}

In [50]:
gcv.best_score_

-18.01263676130663

In [51]:
gcv.best_estimator_.predict(np.array([0.3,0.5,0.7]).reshape(-1,3))

array([21.02083598])

In [52]:
#RandomSearchCV work for if we have n_no of samples
from sklearn.model_selection import RandomizedSearchCV
model = KNeighborsRegressor(n_jobs=-1)
kf = KFold(n_splits = 10)

params = {'n_neighbors':list(range(1,11)),
          'weights':['uniform','distance'],
          'metric':['euclidean','manhattan','cosine']
         }

rcv = RandomizedSearchCV(model,param_distributions = params, cv= kf, scoring ='neg_mean_absolute_error')
rcv.fit(x,df['Y'])


RandomizedSearchCV(cv=KFold(n_splits=10, random_state=None, shuffle=False),
                   estimator=KNeighborsRegressor(n_jobs=-1),
                   param_distributions={'metric': ['euclidean', 'manhattan',
                                                   'cosine'],
                                        'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8,
                                                        9, 10],
                                        'weights': ['uniform', 'distance']},
                   scoring='neg_mean_absolute_error')

In [53]:
rcv.best_params_

{'weights': 'distance', 'n_neighbors': 4, 'metric': 'manhattan'}

In [54]:
rcv.best_score_

-18.042162668942073

In [55]:
rcv.best_estimator_

KNeighborsRegressor(metric='manhattan', n_jobs=-1, n_neighbors=4,
                    weights='distance')

In [56]:
rcv.best_estimator_ .fit(x,df['Y'])

KNeighborsRegressor(metric='manhattan', n_jobs=-1, n_neighbors=4,
                    weights='distance')

In [57]:
rcv.best_estimator_ .predict(np.array([0.3,0.5,0.7]).reshape(-1,3))

array([23.33718155])

In [ ]:
cylinder = pd.read_csv("/content/bands.data")
cylinder

19910108  X126  TVGUIDE  25503  YES  KEY YES.1  BENTON  GALLATIN  \
0    19910109  X266  TVGUIDE  25503  YES  KEY   YES  BENTON  GALLATIN   
1    19910104    B7   MODMAT  47201  YES  KEY   YES  BENTON  GALLATIN   
2    19910104  T133   MASSEY  39039  YES  KEY   YES  BENTON  GALLATIN   
3    19910111   J34    KMART  37351   NO  KEY   YES  BENTON  GALLATIN   
4    19910104  T218   MASSEY  38039  YES  KEY   YES  BENTON  GALLATIN   
..        ...   ...      ...    ...  ...  ...   ...     ...       ...   
535  19941005  aa66    kmart  85813    ?  key     ?       ?  gallatin   
536  19941009   j44     best  38064    ?  key     ?       ?  gallatin   
537  19941009  aa58    kmart  85814    ?  key     ?       ?  gallatin   
538  19941010  aa70    kmart  85814    ?  key     ?       ?  gallatin   
539  19941010   j70     best  38064    ?  key     ?       ?  gallatin   

     UNCOATED  ...  36.4  0 0.1  2.5    1  34  40     105  100    band  
0    UNCOATED  ...  38.5  0   0  2.5  0.7  34  40     105  100  noband  
1    UNCOATED  ...  39.8  0   0  2.8  0.9  40  40  103.87  100  noband  
2    UNCOATED  ...  38.8  0   0  2.5  1.3  40  40  108.06  100  noband  
3    UNCOATED  ...  42.5  5   0  2.3  0.6  35  40  106.67  100  noband  
4    UNCOATED  ...  37.6  5   0  2.5  0.8  40  40  103.87  100  noband  
..        ...  ...   ... ..  ..  ...  ...  ..  ..     ...  ...     ...  
535     super  ...     ?  ?   ?    1    1   ?  40   112.5  100    band  
536     super  ...     ?  ?   ?    0    0   ?  40     110  100    band  
537     super  ...     ?  ?   ?  2.7  2.8   ?  40     108  100    band  
538     super  ...     ?  ?   ?  1.5  2.3   ?  40     108  100    band  
539     super  ...     ?  ?   ?  2.5    1   ?  40   108.1  100    band  

[540 rows x 40 columns]

In [ ]:
cylinder.dtypes

19910108       object
X126           object
TVGUIDE        object
25503          object
YES            object
KEY            object
YES.1          object
BENTON         object
GALLATIN       object
UNCOATED       object
UNCOATED.1     object
NO             object
LINE           object
YES.2          object
Motter94       object
821            object
2             float64
TABLOID        object
NorthUS        object
1911           object
55             object
46             object
0.2            object
17             object
78             object
0.75           object
20             object
13.1           object
1700           object
50.5           object
36.4           object
0              object
0.1            object
2.5            object
1              object
34             object
40             object
105            object
100            object
band           object
dtype: object

In [ ]:
# Since column headers are not correct, assign corrections to a variable for later use

column_headers = ['timestamp','cylinder number','customer','job number','grain screened',
                  'ink color','proof on ctd ink','blade mfg','cylinder division','paper type',
                  'ink type','direct steam','solvent type','type on cylinder','press type','press',
                  'unit number','cylinder size','paper mill location','plating tank','proof cut',
                  'viscosity','caliper','ink temperature','humifity','roughness','blade pressure',
                  'varnish pct','press speed','ink pct','solvent pct','ESA Voltage','ESA Amperage','wax',
                  'hardener','roller durometer','current density','anode space ratio','chrome content','band type'
                  ]


In [ ]:
# Update data with corrected headers using previously defined variable
cylinder = pd.read_csv('/content/bands.data', header=None, names=column_headers)
cylinder.head()

timestamp cylinder number customer job number grain screened ink color  \
0  19910108            X126  TVGUIDE      25503            YES       KEY   
1  19910109            X266  TVGUIDE      25503            YES       KEY   
2  19910104              B7   MODMAT      47201            YES       KEY   
3  19910104            T133   MASSEY      39039            YES       KEY   
4  19910111             J34    KMART      37351             NO       KEY   

  proof on ctd ink blade mfg cylinder division paper type  ... solvent pct  \
0              YES    BENTON          GALLATIN   UNCOATED  ...        36.4   
1              YES    BENTON          GALLATIN   UNCOATED  ...        38.5   
2              YES    BENTON          GALLATIN   UNCOATED  ...        39.8   
3              YES    BENTON          GALLATIN   UNCOATED  ...        38.8   
4              YES    BENTON          GALLATIN   UNCOATED  ...        42.5   

  ESA Voltage ESA Amperage  wax hardener roller durometer  current density  \
0           0            0  2.5        1               34               40   
1           0            0  2.5      0.7               34               40   
2           0            0  2.8      0.9               40               40   
3           0            0  2.5      1.3               40               40   
4           5            0  2.3      0.6               35               40   

  anode space ratio chrome content band type  
0               105            100      band  
1               105            100    noband  
2            103.87            100    noband  
3            108.06            100    noband  
4            106.67            100    noband  

[5 rows x 40 columns]

In [ ]:
# Check for blank values
cylinder.isnull().sum()

timestamp              0
cylinder number        0
customer               0
job number             0
grain screened         0
ink color              0
proof on ctd ink       0
blade mfg              0
cylinder division      0
paper type             0
ink type               0
direct steam           0
solvent type           0
type on cylinder       0
press type             0
press                  0
unit number            0
cylinder size          1
paper mill location    1
plating tank           1
proof cut              1
viscosity              1
caliper                1
ink temperature        2
humifity               2
roughness              2
blade pressure         2
varnish pct            2
press speed            2
ink pct                2
solvent pct            2
ESA Voltage            2
ESA Amperage           2
wax                    2
hardener               2
roller durometer       2
current density        2
anode space ratio      2
chrome content         2
band type              2


In [ ]:
#check the data types
cylinder.dtypes

timestamp               object
cylinder number         object
customer                object
job number              object
grain screened          object
ink color               object
proof on ctd ink        object
blade mfg               object
cylinder division       object
paper type              object
ink type                object
direct steam            object
solvent type            object
type on cylinder        object
press type              object
press                   object
unit number            float64
cylinder size           object
paper mill location     object
plating tank            object
proof cut               object
viscosity               object
caliper                 object
ink temperature         object
humifity                object
roughness               object
blade pressure          object
varnish pct             object
press speed             object
ink pct                 object
solvent pct             object
ESA Voltage             object
ESA Ampe

In [ ]:
from mlxtend.preprocessing import TransactionEncoder

#list/Array of lists
te = TransactionEncoder()
encoded_data = pd.DataFrame(te.fit_transform(cylinder['band type'].str.split(',')).astype(int),columns = te.columns_)

TypeError: ignored

In [ ]:
# Remove rows with missing values
cylinder.dropna(inplace=True)

# Check for missing values again
print(cylinder.isnull().sum())

timestamp              0
cylinder number        0
customer               0
job number             0
grain screened         0
ink color              0
proof on ctd ink       0
blade mfg              0
cylinder division      0
paper type             0
ink type               0
direct steam           0
solvent type           0
type on cylinder       0
press type             0
press                  0
unit number            0
cylinder size          0
paper mill location    0
plating tank           0
proof cut              0
viscosity              0
caliper                0
ink temperature        0
humifity               0
roughness              0
blade pressure         0
varnish pct            0
press speed            0
ink pct                0
solvent pct            0
ESA Voltage            0
ESA Amperage           0
wax                    0
hardener               0
roller durometer       0
current density        0
anode space ratio      0
chrome content         0
band type              0


In [ ]:
cylinder.shape

(539, 40)

In [ ]:
cylinder.dtypes

timestamp               object
cylinder number         object
customer                object
job number              object
grain screened          object
ink color               object
proof on ctd ink        object
blade mfg               object
cylinder division       object
paper type              object
ink type                object
direct steam            object
solvent type            object
type on cylinder        object
press type              object
press                   object
unit number            float64
cylinder size           object
paper mill location     object
plating tank            object
proof cut               object
viscosity               object
caliper                 object
ink temperature         object
humifity                object
roughness               object
blade pressure          object
varnish pct             object
press speed             object
ink pct                 object
solvent pct             object
ESA Voltage             object
ESA Ampe

In [ ]:
cylinder['band type'].unique()

array(['band', 'noband'], dtype=object)

In [ ]:
cylinder['band type']

0        band
1      noband
2      noband
3      noband
4      noband
        ...  
536      band
537      band
538      band
539      band
540      band
Name: band type, Length: 539, dtype: object

In [ ]:
from mlxtend.preprocessing import TransactionEncoder

#list/Array of lists
te = TransactionEncoder()
data = pd.DataFrame(te.fit_transform(cylinder['band type'].str.split(',')).astype(int),columns = te.columns_)

In [ ]:
te.columns_

['band', 'noband']

In [ ]:
cylinder['band type'].values.reshape(-1,1)

array([['band'],
       ['noband'],
       ['noband'],
       ['noband'],
       ['noband'],
       ['noband'],
       ['noband'],
       ['noband'],
       ['band'],
       ['noband'],
       ['noband'],
       ['band'],
       ['band'],
       ['band'],
       ['noband'],
       ['band'],
       ['noband'],
       ['noband'],
       ['noband'],
       ['noband'],
       ['noband'],
       ['noband'],
       ['noband'],
       ['band'],
       ['band'],
       ['band'],
       ['noband'],
       ['noband'],
       ['band'],
       ['band'],
       ['noband'],
       ['noband'],
       ['noband'],
       ['noband'],
       ['band'],
       ['noband'],
       ['band'],
       ['noband'],
       ['noband'],
       ['noband'],
       ['noband'],
       ['noband'],
       ['noband'],
       ['noband'],
       ['noband'],
       ['noband'],
       ['noband'],
       ['noband'],
       ['noband'],
       ['noband'],
       ['band'],
       ['band'],
       ['noband'],
       ['noband'],
    

In [ ]:
cylinder['band type'].shape

(539,)

In [ ]:
# Concatenate the original data with the encoded data
original_data = pd.concat([cylinder, data], axis=1)

In [ ]:
original_data

timestamp cylinder number customer job number grain screened ink color  \
0    19910108            X126  TVGUIDE      25503            YES       KEY   
1    19910109            X266  TVGUIDE      25503            YES       KEY   
2    19910104              B7   MODMAT      47201            YES       KEY   
3    19910104            T133   MASSEY      39039            YES       KEY   
4    19910111             J34    KMART      37351             NO       KEY   
..        ...             ...      ...        ...            ...       ...   
538  19941009            aa58    kmart      85814              ?       key   
539  19941010            aa70    kmart      85814              ?       key   
540  19941010             j70     best      38064              ?       key   
521       NaN             NaN      NaN        NaN            NaN       NaN   
522       NaN             NaN      NaN        NaN            NaN       NaN   

    proof on ctd ink blade mfg cylinder division paper type  ... ESA Amperage  \
0                YES    BENTON          GALLATIN   UNCOATED  ...            0   
1                YES    BENTON          GALLATIN   UNCOATED  ...            0   
2                YES    BENTON          GALLATIN   UNCOATED  ...            0   
3                YES    BENTON          GALLATIN   UNCOATED  ...            0   
4                YES    BENTON          GALLATIN   UNCOATED  ...            0   
..               ...       ...               ...        ...  ...          ...   
538                ?         ?          gallatin      super  ...            ?   
539                ?         ?          gallatin      super  ...            ?   
540                ?         ?          gallatin      super  ...            ?   
521              NaN       NaN               NaN        NaN  ...          NaN   
522              NaN       NaN               NaN        NaN  ...          NaN   

     wax hardener roller durometer current density anode space ratio  \
0    2.5        1               34              40               105   
1    2.5      0.7               34              40               105   
2    2.8      0.9               40              40            103.87   
3    2.5      1.3               40              40            108.06   
4    2.3      0.6               35              40            106.67   
..   ...      ...              ...             ...               ...   
538  2.7      2.8                ?              40               108   
539  1.5      2.3                ?              40               108   
540  2.5        1                ?              40             108.1   
521  NaN      NaN              NaN             NaN               NaN   
522  NaN      NaN              NaN             NaN               NaN   

     chrome content band type band noband  
0               100      band  1.0    0.0  
1               100    noband  0.0    1.0  
2               100    noband  0.0    1.0  
3               100    noband  0.0    1.0  
4               100    noband  0.0    1.0  
..              ...       ...  ...    ...  
538             100      band  1.0    0.0  
539             100      band  NaN    NaN  
540             100      band  NaN    NaN  
521             NaN       NaN  1.0    0.0  
522             NaN       NaN  1.0    0.0  

[541 rows x 42 columns]

In [ ]:
data.values.reshape(-1,1)

array([[1],
       [0],
       [0],
       ...,
       [0],
       [1],
       [0]])

In [ ]:
data.shape

(539, 2)